"""Hunyuan3D AI 3D-generation integration tools."""

import logging

from mcp.server.fastmcp import Context
from mcp.server.fastmcp.exceptions import ToolError

from ..app import mcp
from ..connection import get_blender_connection
from ._envelope import ok

logger = logging.getLogger("BlenderMCPServer")


@mcp.tool()
def get_hunyuan3d_status(ctx: Context, user_prompt: str = "") -> dict:
    """
    Check if Hunyuan3D integration is enabled in Blender.
    Returns whether Hunyuan3D features are available.
    """
    try:
        blender = get_blender_connection()
        result = blender.send_command("get_hunyuan3d_status")
        return ok(result)
    except Exception as e:
        logger.error(f"Error checking Hunyuan3D status: {e}")
        raise ToolError(f"Error checking Hunyuan3D status: {e}") from e


@mcp.tool()
async def generate_hunyuan3d_model(
    ctx: Context,
    text_prompt: str | None = None,
    input_image_url: str | None = None,
    user_prompt: str = "",
) -> dict:
    """
    Generate 3D asset using Hunyuan3D by providing either text description, image reference,
    or both for the desired asset, and import the asset into Blender.
    The 3D asset has built-in materials.

    Parameters:
    - text_prompt: (Optional) A short description of the desired model in English/Chinese.
    - input_image_url: (Optional) The local or remote url of the input image. Accepts None if only using text prompt.
    - user_prompt: The user's own words describing what they want, quoted verbatim (do not paraphrase or summarise). Pass the same goal on every call in a multi-step task so each action is linked to the intent behind it. Never substitute your own sub-goal, plan step, or status text; if the user has given no new instruction, repeat their previous words unchanged.

    Returns a job_id (format: "job_xxx") indicating the task is in progress; poll with poll_hunyuan_job_status.
    """
    try:
        blender = get_blender_connection()
        result = blender.send_command(
            "create_hunyuan_job",
            {
                "text_prompt": text_prompt,
                "image": input_image_url,
            },
        )
        if "JobId" in result.get("Response", {}):
            job_id = result["Response"]["JobId"]
            return ok({"job_id": f"job_{job_id}"})
        return ok(result)
    except Exception as e:
        logger.error(f"Error generating Hunyuan3D task: {e}")
        raise ToolError(f"Error generating Hunyuan3D task: {e}") from e


@mcp.tool()
def poll_hunyuan_job_status(
    ctx: Context,
    job_id: str | None = None,
    user_prompt: str = "",
) -> dict:
    """
    Check if the Hunyuan3D generation task is completed.

    For Hunyuan3D:
        Parameters:
        - job_id: The job_id given in the generate model step.

        Returns the generation task status. The task is done if status is "DONE".
        The task is in progress if status is "RUN".
        If status is "DONE", returns ResultFile3Ds with one or more downloadable model URLs.
        Prefer a .glb URL when present (self-contained with materials); otherwise use a .zip/.obj asset URL.
        This is a polling API, so only proceed if the status are finally determined ("DONE" or some failed state).

    - user_prompt: The user's own words describing what they want, quoted verbatim (do not paraphrase or summarise). Pass the same goal on every call in a multi-step task so each action is linked to the intent behind it. Never substitute your own sub-goal, plan step, or status text; if the user has given no new instruction, repeat their previous words unchanged.
    """
    try:
        blender = get_blender_connection()
        result = blender.send_command("poll_hunyuan_job_status", {"job_id": job_id})
        return ok(result)
    except Exception as e:
        logger.error(f"Error polling Hunyuan3D job status: {e}")
        raise ToolError(f"Error polling Hunyuan3D job status: {e}") from e


@mcp.tool()
async def import_generated_asset_hunyuan(
    ctx: Context,
    name: str,
    zip_file_url: str,
    user_prompt: str = "",
) -> dict:
    """
    Import the asset generated by Hunyuan3D after the generation task is completed.

    Parameters:
    - name: The name of the object in scene
    - zip_file_url: A model URL from ResultFile3Ds. Prefer a .glb URL when available; .zip/.obj URLs still work as a fallback.
    - user_prompt: The user's own words describing what they want, quoted verbatim (do not paraphrase or summarise). Pass the same goal on every call in a multi-step task so each action is linked to the intent behind it. Never substitute your own sub-goal, plan step, or status text; if the user has given no new instruction, repeat their previous words unchanged.
    """
    try:
        blender = get_blender_connection()
        result = blender.send_command(
            "import_generated_asset_hunyuan",
            {"name": name, "zip_file_url": zip_file_url},
        )
        return ok(result, changed_objects=[name])
    except Exception as e:
        logger.error(f"Error importing Hunyuan3D asset: {e}")
        raise ToolError(f"Error importing Hunyuan3D asset: {e}") from e
